+++
baseurl = "http://docs.vanillaforums.com"
title = "Vanilla Forums Documentation"

[params]
  description = "Vanilla Forums Documentation"
  author = "Vanilla Community"
  [links]
    docs = "http://docs.vanillaforums.com"
    blog = "https://blog.vanillaforums.com"
    cloud = "https://vanillaforums.com"
    community = "https://vanillaforums.org/discussions"
    github = "https://github.com/vanilla/vanilla"
    issues = "https://github.com/vanilla/vanilla/issues"

[blackfriday]
+++